### ISSUE TITLE
ImportError: No module named 'webapp'

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/cs251-toolkit#106]
```
$ cs251tk -n --record hw1
Traceback (most recent call last):
  File "/usr/local/bin/cs251tk", line 7, in <module>
    from cs251tk.toolkit.__main__ import main
  File "/usr/local/lib/python3.5/dist-packages/cs251tk/toolkit/__main__.py", line 18, in <module>
    from webapp import server
ImportError: No module named 'webapp'
ERROR: Job failed: exit code 1
```

Fallout from #104

**Comment by maxnz** [comment]
I'm not getting that error, even after installing from pip. I'll try it in a VM and see if I get it there.

**Comment by maxnz** [comment]
What machine gave this error?

**Comment by hawkrives** [comment]
@maxnz A GitLab CI runner running the v2.5.0 docker image, but it seems like you're past needing that information now ;)
