### ISSUE TITLE
Error running on mac after install

### ISSUE THREAD

**Issue by hannesmcman** [StoDevX/cs251-toolkit#115]
After installing on mac and running `cs251tk`, I get the following error:
```
Traceback (most recent call last):
  File "/Users/Hannes/Library/Python/3.7/bin/cs251tk", line 11, in <module>
    load_entry_point('cs251tk==2.5.1', 'console_scripts', 'cs251tk')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/Hannes/Library/Python/3.7/lib/python/site-packages/cs251tk/toolkit/__main__.py", line 18, in <module>
    from ..webapp import server
ModuleNotFoundError: No module named 'cs251tk.webapp'
```
Any ideas?

**Comment by maxnz** [comment]
It looks like pip isn't including that module for some reason. Any ideas @hawkrives?

**Comment by maxnz** [comment]
How is the SOURCES.txt file in cs251tk.egg-info created? That seems to include all the files except the ones in webapp.

**Comment by maxnz** [comment]
Is it possible that an __init__.py is required in the webapp package?

**Comment by hawkrives** [comment]
No idea. Python packaging has always been a black art to me. 

I can take this on and try to investigate. 

All the egg stuff is generated by setup.py invocations, for what it's worth.

**Comment by maxnz** [comment]
Yup. It's the __init__.py. When `python3 setup.py sdist bdist_wheel` is called, it only includes the package if there is a __init__.py there. I tested with test.pypi.org and it worked.
